### ISSUE TITLE
config.jura shouldn't be in the $HOME dir

### ISSUE THREAD

**Issue by ManuLinares** [Nooberieno/jura#13]
The config should be in $HOME/.config/filename
or be a hidden dot file in the $HOME dir.

**Comment by Nooberieno** [comment]
I am aware of this issue and this will be fixed in the 5.0 release. 

I am currently working on finding a more effective and elegant solution for the entire configuration code all together and maybe making that its own program

The current plan is for the config to be located in $HOME/.config/jura/{configfile} or in the $XDG_CONFIG_HOME if that environnement variable is set. 

I am currently busy with my exams and will get to work once those are over

**Comment by Nooberieno** [comment]
This has been changed to $HOME/.config/config.jura for now, i still want to redo the configuration code at some point, but i have been putting of updating this project for way to long, thank you for your patience. I will close this issue as it has will be solved with the 5.0 release

**Comment by ManuLinares** [comment]
No worries, I hope you don't mind me using it as an example for teaching. Thank you very much for sharing!
